### ISSUE TITLE
64-bit version?

### ISSUE THREAD

**Issue by Ben-Voris** [blumu/NppColumnSort#3]
Do you plan to create a version of this plugin for 64-bit Notepad++ ?

**Comment by blumu** [comment]
Both 32bit and 64bit version are already supported.

**Comment by Ben-Voris** [comment]
There is no 64-bit version in the plugin manager. I see no directions for installing it here.

**Comment by blumu** [comment]
You may need to install it manually. See instructions at https://github.com/blumu/NppColumnSort/blob/master/README.md

**Comment by Ben-Voris** [comment]
This paragraph starts with, “You first need to build the project in Visual Studio.”  I interpret that to mean that I must build the plug-in myself. Not so?

**Comment by blumu** [comment]
Try downloading the x64 artifacts from https://ci.appveyor.com/project/blumu/nppcolumnsort/build/job/bbq8lsdjn5ifg6s3/artifacts

## Instructions:
- Download [64bit of the plugin DLL](https://ci.appveyor.com/api/buildjobs/rellc5cqql57sgb3/artifacts/NppColumnSort.dll)
- Copy it under `C:\Program Files\Notepad++\plugins`
- Restart notepad++

![image](https://user-images.githubusercontent.com/3913258/41308043-b0481a56-6e2f-11e8-8a08-9e10431de2f7.png)

**Comment by blumu** [comment]
Released on GitHub: https://github.com/blumu/NppColumnSort/releases/tag/1.0.0.2-64bits
